### ISSUE TITLE
Remove usage of manifest variable in templates

### ISSUE THREAD

**Issue by enzy** [manGoweb/mango-cli-example#20]
It's hard to remove on multiple places when it's unwanted. Extract it to single file or remove completely.

**Comment by Onset** [comment]
Don't remove it then. I don't see any case of an unwanted link to the `manifest.json`. Can you provide any example?

**Comment by enzy** [comment]
https://github.com/manGoweb/mango-cli-example/search?utf8=%E2%9C%93&q=manifest.&type=
