### ISSUE TITLE
Update example to support mango-builder

### ISSUE THREAD

**Issue by ViliamKopecky** [manGoweb/mango-cli-example#28]
Using `assetPath` fallback, and usage. Mangbo builder prefills `assetPath` with some hash string path like `/1b53aaea022c035893e85b80bfe070df/`.

- In layout.pug define fallback: `- assetPath = assetPath || '/'`
- use `assetPath` variable across templates

Builder also has problems with relative template paths (eg `../mixins/foobar`), which must be replaced with paths relative to project directory (eg `/src/templates/mixins/foobar`), but this would be better fixed in `mango-cli`, but thats probably not very easy.

**Comment by enzy** [comment]
Paths problem in https://github.com/manGoweb/mango-cli/issues/179
